CREATE OR REPLACE FUNCTION ABREV_END (ENDERECO IN VARCHAR2)

RETURN VARCHAR2

IS

RESULT VARCHAR(40);

BEGIN

RESULT := SUBSTR(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ENDERECO,'BLOCO','BL'), 'CONJUNTO', 'CONJ'), 'CASA', 'CS'), 'LOTE', 'LT'), 'CHACARA', 'CHAC'), 'QUADRA', 'QD'), 0, 40);

RETURN (RESULT);

END;
