CREATE OR REPLACE FUNCTION FORMATAR_TELEFONE (P_DDD VARCHAR2,P_TELEFONE VARCHAR2)

RETURN VARCHAR2 IS

V_TELEFONE VARCHAR2 (30);
V_TELEFONE_FORMATADO VARCHAR2(30);

BEGIN

V_TELEFONE := REPLACE(TRIM(REPLACE(P_DDD,'-','')) || TRIM(REPLACE(P_TELEFONE,'-','')),'.','');

IF LENGTH(V_TELEFONE) = 8 THEN
  V_TELEFONE_FORMATADO :=  SUBSTR(V_TELEFONE,1,4) || '-' || SUBSTR(V_TELEFONE,5,4);
END IF;

IF LENGTH(V_TELEFONE) = 9 THEN
  V_TELEFONE_FORMATADO :=    SUBSTR(V_TELEFONE,1,5) || '-' || SUBSTR(V_TELEFONE,6,4);
END IF;

IF LENGTH(V_TELEFONE) = 10 THEN
  V_TELEFONE_FORMATADO :=    '(' || SUBSTR(V_TELEFONE,1,2) || ')' || SUBSTR(V_TELEFONE,3,4) || '-' || SUBSTR(V_TELEFONE,7,4);
END IF;

IF LENGTH(V_TELEFONE) = 11 THEN
  V_TELEFONE_FORMATADO :=    '(' || SUBSTR(V_TELEFONE,1,2) || ')' || SUBSTR(V_TELEFONE,3,5) || '-' || SUBSTR(V_TELEFONE,8,4);
END IF;

IF LENGTH(V_TELEFONE) = 12 THEN
  V_TELEFONE_FORMATADO :=    SUBSTR(V_TELEFONE,1,2) || '(' || SUBSTR(V_TELEFONE,3,2) || ')' || SUBSTR(V_TELEFONE,5,4) || '-' || SUBSTR(V_TELEFONE,9,4);
END IF;

IF LENGTH(V_TELEFONE) = 13 THEN
  V_TELEFONE_FORMATADO :=    SUBSTR(V_TELEFONE,1,2) || '(' || SUBSTR(V_TELEFONE,3,2) || ')' || SUBSTR(V_TELEFONE,5,5) || '-' || SUBSTR(V_TELEFONE,10,4);
END IF;

IF LENGTH(V_TELEFONE) > 13 THEN
  V_TELEFONE_FORMATADO := P_DDD || P_TELEFONE;
END IF;

RETURN(V_TELEFONE_FORMATADO);

END;
