CREATE OR REPLACE FUNCTION IDADE(PCODPESSOA VARCHAR, PDTBASE DATE DEFAULT NULL) RETURN INTEGER IS

IDADE INTEGER;

BEGIN

SELECT ANOSENTREDATAS(DT_NASC, NVL(PDTBASE, SYSDATE)) INTO IDADE -- ANO ENTRE DATAS É OUTRA FUNCAO
  FROM TABELA_PESSOA A
 WHERE A.COD_PESSOA = PCODPESSOA;

RETURN IDADE;

END;
