CREATE OR REPLACE FUNCTION INVERTEMESANO(S STRING)

RETURN STRING IS

POSICAO INTEGER;
TEMP    LONG;
TEMP1   LONG;

BEGIN

IF (S = '  /    ') OR (S = '    /  ') OR (S = '       ') OR (LENGTH(S) < 7) OR (NVL(S, ' ') = ' ') THEN
   RETURN S;
END IF;

IF POS('/', S) = 0 THEN
   RAISE_APPLICATION_ERROR(-20000, 'MES E ANO INFORMADO EM FORMATO INVÁLIDO: ' || S);
END IF;

TEMP    := SUBSTR(S, 8, LENGTH(S) - 7);

TEMP1   := SUBSTR(S, 1, 7);

POSICAO := 1;

LOOP
  EXIT WHEN SUBSTR(TEMP1, POSICAO, 1) = '/';
BEGIN
  POSICAO := POSICAO + 1;
  EXCEPTION
    WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20000, 'ERRO AO INVERTER MES E ANO EM: ' || S);
  END;
END LOOP;

RETURN(SUBSTR(TEMP1, POSICAO + 1, LENGTH(TEMP1) - POSICAO) || '/' ||

SUBSTR(TEMP1, 1, POSICAO - 1) || TEMP);

END;



