CREATE OR REPLACE FUNCTION LINHA_DIGITAVEL (CODBOLETO NUMBER, VENCIMENTO DATE)
RETURN STRING
IS
RETORNO VARCHAR2(150);
COD_BOLETO VARCHAR2(10);
FATOR_VENCIMENTO VARCHAR2(100);
BASE_VENCIMENTO DATE;
VALOR_BOLETO VARCHAR2(15);
COD_BARRA_PARCIAL VARCHAR2(100);
COD_BARRA VARCHAR2(100);
SOMA NUMBER(10);
MULTIPLICADOR NUMBER(10);
V1 NUMBER(3);
V2 NUMBER(3);
V3 NUMBER(3);
V4 NUMBER(3);
DIGITO NUMBER(1);
VALOR NUMBER(10);
DIGITO_GERAL NUMBER(2);
GRUPO1 VARCHAR(15);
GRUPO2 VARCHAR(15);
GRUPO3 VARCHAR(15);
V_DIGITO VARCHAR2(10);
D_GRUPO1 VARCHAR(1);
D_GRUPO2 VARCHAR(1);
D_GRUPO3 VARCHAR(1);
COD_DIGITAVEL_PARCIAL VARCHAR(100);
COD_DIGITAVEL VARCHAR(150);

BEGIN

/* BOLETO BB */

-- COD_BOLETO TAMANHO 10
SELECT LPAD(B.COD_BOLETOETO,10,0) INTO COD_BOLETO
  FROM TABELA_BOLETO B
 WHERE B.COD_BOLETOOLETO = CODBOLETOETO;

-- FATOR VENCIMENTO
BASE_VENCIMENTO := '07/10/1997';
FATOR_VENCIMENTO := VENCIMENTO - BASE_VENCIMENTO;


-- VALOR BOLETO
SELECT TRIM(TO_CHAR(B.VALOR,'999999990D99')) INTO VALOR_BOLETO
  FROM TABELA_BOLETO B
 WHERE B.COD_BOLETO = CODBOLETO; --9822420
 
VALOR_BOLETO :=  LPAD(REPLACE(REPLACE(VALOR_BOLETO,',',''),'.',''),10,'0');

-- CODIGO DE BARRAS PARCIAL
COD_BARRA_PARCIAL := '001'||'9'||FATOR_VENCIMENTO||VALOR_BOLETO||'000000'||'2856029'||COD_BOLETO||'17';

-- DIGITO GERAL
SOMA := 0;
MULTIPLICADOR := 2;
COD_BARRA_PARCIAL := LPAD(COD_BARRA_PARCIAL,43,'0');

V1 := 42;
WHILE V1 >= 0 LOOP
  DIGITO := TO_NUMBER(SUBSTR(COD_BARRA_PARCIAL,V1+1,1));
  VALOR  := DIGITO * MULTIPLICADOR;
  MULTIPLICADOR := MULTIPLICADOR + 1;
  
  IF MULTIPLICADOR > 9
    THEN MULTIPLICADOR := 2;
  END IF;
  
  SOMA := SOMA+VALOR;  

  V1 := V1-1;
END LOOP;

IF ((MOD(SOMA, 11) = 0) OR (MOD(SOMA, 11) = 1) OR (MOD(SOMA, 11) = 10))
  THEN DIGITO_GERAL := 1;
ELSE DIGITO_GERAL  := 11 - (MOD(SOMA, 11));
END IF;

-- CODIGO DE BARRAS
COD_BARRA := '001'||'9'||TO_CHAR(DIGITO_GERAL)||FATOR_VENCIMENTO||VALOR_BOLETO||'000000'||'2856029'||COD_BOLETO||'17';

-- GRUPO 1
GRUPO1 := '001'||'9'||SUBSTR(COD_BARRA,20,5);

-- GRUPO 2
GRUPO2 := SUBSTR(COD_BARRA,25,10);

-- GRUPO 3
GRUPO3 := SUBSTR(COD_BARRA,35,10);

-- DIGITO GRUPO 1
SOMA := 0;
V_DIGITO := LPAD(GRUPO1,10,'0');

V2 := 9;
WHILE V2 >= 0 LOOP
  MULTIPLICADOR := (MOD(V2,2)) + 1;
  DIGITO := TO_NUMBER(SUBSTR(V_DIGITO,V2+1,1));
  VALOR  := DIGITO * MULTIPLICADOR; 
    
  IF VALOR > 9
    THEN VALOR := VALOR - 9;
  END IF;
  
  SOMA := SOMA+VALOR;  
  V2 := V2-1;

END LOOP;

IF MOD(SOMA,10) = 0
  THEN D_GRUPO1 := 0;
ELSE D_GRUPO1 := 10 - MOD(SOMA,10);
END IF;

-- DIGITO GRUPO 2
SOMA := 0;
V_DIGITO := LPAD(GRUPO2,10,'0');

V3 := 9;
WHILE V3 >= 0 LOOP
  MULTIPLICADOR := (MOD(V3, 2)) + 1;
  DIGITO := TO_NUMBER(SUBSTR(V_DIGITO,V3+1,1));
  VALOR  := DIGITO * MULTIPLICADOR; 
  
  IF VALOR > 9
    THEN VALOR := VALOR - 9;
  END IF;
  
  SOMA := SOMA+VALOR;  
  V3 := V3-1;  
END LOOP;

IF MOD(SOMA,10) = 0
  THEN D_GRUPO2 := 0;
ELSE D_GRUPO2 := 10 - (MOD(SOMA, 10));
END IF;

-- DIGITO GRUPO 3
SOMA := 0;
V_DIGITO := LPAD(GRUPO3,10,'0');

V4 := 9;
WHILE V4 >= 0 LOOP
  MULTIPLICADOR := (MOD(V4, 2)) + 1;
  DIGITO := TO_NUMBER(SUBSTR(V_DIGITO,V4+1,1));
  VALOR  := DIGITO * MULTIPLICADOR; 
  
  IF VALOR > 9
    THEN VALOR := VALOR - 9;
  END IF;
  
  SOMA := SOMA+VALOR; 
  V4 := V4-1;   
END LOOP;

IF (MOD(SOMA, 10)) = 0
  THEN D_GRUPO3 := 0;
ELSE D_GRUPO3 := 10 - (MOD(SOMA,10));
END IF;

-- LINHA DIGITAVEL PARCIAL
COD_DIGITAVEL_PARCIAL := GRUPO1||D_GRUPO1||GRUPO2||D_GRUPO2||GRUPO3||D_GRUPO3||TO_CHAR(DIGITO_GERAL)||FATOR_VENCIMENTO||VALOR_BOLETO;

-- LINHA DIGITAVEL FORMATADA
COD_DIGITAVEL := SUBSTR(COD_DIGITAVEL_PARCIAL,1,5)||'.'||SUBSTR(COD_DIGITAVEL_PARCIAL,6,5)||' '||SUBSTR(COD_DIGITAVEL_PARCIAL,11,5)||'.'||SUBSTR(COD_DIGITAVEL_PARCIAL,16,6)
              ||' '||SUBSTR(COD_DIGITAVEL_PARCIAL,22,5)||'.'||SUBSTR(COD_DIGITAVEL_PARCIAL,27,6)||' '||SUBSTR(COD_DIGITAVEL_PARCIAL,33,1)||' '||SUBSTR(COD_DIGITAVEL_PARCIAL,34,20);


RETORNO := COD_DIGITAVEL;
RETURN(RETORNO);
END;
